### ISSUE TITLE
Project maintainer?

### ISSUE THREAD

**Issue by zabracks** [paulyoder/LinqToExcel#100]
Is this project actively maintained? The most recent commit was on 2015-04-07.

This project has many users that interface with it daily. Could we either add a team of maintainers so that contributions can be made or transfer the project (and nuget permissions) to another repository?

**Comment by RyanDansie** [comment]
I guess the author is not active on here any more but if anyone is volunteering there is an emaila ddres for him on his website: http://yodersolutions.com/#!/contact

**Comment by phawxby** [comment]
I have merge rights to the repo but I no longer work in the .net space, I don't even have visual studio installed. So although I can merge fixes and publish them, that's it, I'd be replying on others for merge approval. Not exactly ideal

**Comment by phawxby** [comment]
Paging @paulyoder, can you give others some collaborator rights please?

**Comment by paulyoder** [comment]
Sorry for delayed response. 

Yes, I can give other collaborators rights. Who wants them?

**Comment by zabracks** [comment]
I'd be happy to help.

**Comment by paulyoder** [comment]
Thanks @zabracks! I just made you a collaborator. 

I still need to give you access to the Nuget account. What's your Nuget username?

**Comment by MorbidKoder** [comment]
This makes me happy. This is one of my favorite libraries. I also have it in use in multiple large production systems.

**Comment by mrworkman** [comment]
Hey @paulyoder, can you give me access to the NuGet account as well? The account's 'mrworkman' there too.

**Comment by paulyoder** [comment]
I just gave you access to the NuGet account @mrworkman

**Comment by paulyoder** [comment]
closing now that @zabracks and @mrworkman are project collaborators
