### ISSUE TITLE
Excel stored in Azure storage

### ISSUE THREAD

**Issue by slowsteadysure** [paulyoder/LinqToExcel#105]
I am uploading excel file to azure storage blob. How to use linqtoexcel to read a file stored in azure storage blob? How to give the file path to linqtoexcel?

**Comment by mrworkman** [comment]
This doesn't sound possible. You'd have to extract the file from the blob, and save it to the file-system where your app can open it. Beyond that, I think this is completely out of scope for LinqToExcel.
