### ISSUE TITLE
Warning from LinqToExcel during compile

### ISSUE THREAD

**Issue by RoyBradley** [paulyoder/LinqToExcel#109]
There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "LinqToExcel, Version=1.10.1.0, Culture=neutral, PublicKeyToken=9c8ea65a58f03f1f, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by LP381** [comment]
I guess your target is "AnyCPU"? If so, then this problem is probably related to issue #110.

**Comment by RoyBradley** [comment]
Thank you, love the LinqToExcel.

Roy

**Comment by mrworkman** [comment]
This sounds "resolved" to me.
