### ISSUE TITLE
NuGet package as AnyCPU

### ISSUE THREAD

**Issue by LP381** [paulyoder/LinqToExcel#110]
Using LinqToExcel in a project compiling with "AnyCPU" is problematic, as you have to decide between the NuGet packages LinqToExcel (x86) or LinkToExcel_x64 (breaking it for one of the two).

It is possible to compile LinqToExcel with AnyCPU though. I remember to have read in some forum, that you ran with this into some problems at the time. Now it seems to work without any issues.
Using the created .dll works as expected.

Would it be possible to update the NuGet package to target AnyCPU? Bonus would be, that the _x64 package can be dropped and one package would be enough.

**Comment by tugberkugurlu** [comment]
👍 to this, it's causing problems.

**Comment by mrworkman** [comment]
Done in 2.0.0-PRERELEASE.
