### ISSUE TITLE
Data edit in excel document

### ISSUE THREAD

**Issue by olegbevz** [paulyoder/LinqToExcel#115]
Hello gents,

I am a great fan of LinqToExcel project. The library simplifies work with excel files significantly. But unfortunately in my project I need also to edit excel files. 
Do you have any plans to add excel edit support to the library?
As I understand standard OledbConnection is used in background. Thus INSERT statements can be executed against the excel document. Right?

**Comment by mrworkman** [comment]
Although the back-end database can do INSERTs, Linq can only query data. Doing insertions/edits would require a completely different mechanism. You can use an OledbConnection directly to do any inserts you need.
