### ISSUE TITLE
not working with office 365 pro plus

### ISSUE THREAD

**Issue by mail2soumenpal** [paulyoder/LinqToExcel#116]
office 365 pro plus is installed in my system, whenever  i am trying to use the below code, it throws error -
            string pathToExcelFile = "" + @"D:\Book1.xlsx";

            string sheetName = "Sheet1";

            var excelFile = new ExcelQueryFactory(pathToExcelFile);
            var getData = from a in excelFile.Worksheet(sheetName) select a;
            string getInfo = String.Empty;

            foreach (var a in getData)
            {
                getInfo += "Name: " + a["Name"] + "; Phone: " + a["Phone"] + ">>   ";

            }
            textBox1.Text = getInfo;

please return back with solution ASAP its urgent. I am using latest version of linqtosql from nuget
![error](https://cloud.githubusercontent.com/assets/8451102/25985894/ab1ae4f8-370a-11e7-841d-b06ed6297d13.png)

**Comment by unickq** [comment]
Same issue here
The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.'

**Comment by mrworkman** [comment]
You need to install the [Microsoft Access Database Engine](https://www.microsoft.com/en-in/download/details.aspx?id=13255) - either the 32bit, or the 64bit version, depending on your project settings.
