### ISSUE TITLE
Unable to specify custom delimiter and/or text qualifier in Query Args

### ISSUE THREAD

**Issue by sbrett9** [paulyoder/LinqToExcel#117]
Howdy,

Nice library.
Is there any way to possibly get the ability to specify custom delimiters and/or text qualifiers the connection string when working with LinqToExcel and csv files?
Currently the OLEDB connection string parameters are not exposed for customization.

I have a usage scenario where I'd like to use LinqToExcel  but my queries need to operate over csv files that have variability in their delimiters and text qualifiers.
Thanks.

**Comment by tsage2012** [comment]
Any update on this? It would be extremely helpful to have support for this. I am parsing CSV files that use a pipe instead of a comma since comma's can appear in the data. So having the option to specify the delimiter would be helpful.

Thanks,
Tim

**Comment by peteriehl** [comment]
Can you elaborate on this? Are you merely looking to "use the tool w/ non-comma delimiters"? or are you looking to make this declaration in the connection string?

**Comment by mrworkman** [comment]
Honestly, if you want good CSV parsing, if go for something like this: https://joshclose.github.io/CsvHelper/

**Comment by tsage2012** [comment]
I was looking to extent the behavior of the reader in order to specify the delimiters, so I could still use the LinqToExcel API

**Comment by tsage2012** [comment]
Thanks for the tip referencing CsvHelper. That did the trick for me. Seems LinqToExcel is great for Excel files and simple CSV files using a comma as the delimiter. However, outside that, more help is required.

Thanks again,
Tim

**Comment by mrworkman** [comment]
No prob. ;)
