### ISSUE TITLE
Property to column mapping with dot in column name

### ISSUE THREAD

**Issue by tomaspaul** [paulyoder/LinqToExcel#128]
Hi, I would like to use this Property to column mapping:
`excel.AddMapping<Result>(x => x.SampleId, "Testprobe Nr.");`

My Excel worksheet column name is `Testprobe Nr.`
It seems that dot in column name cannot be used. I get null value for x.SampleId property.

If I rename column to `Testprobe Nr` and add following mapping, the property is mapped and filled with value from worksheet.
`excel.AddMapping<Result>(x => x.SampleId, "Testprobe Nr");`

My test workbook:
[PR17R5570.xlsx](https://github.com/paulyoder/LinqToExcel/files/1382644/PR17R5570.xlsx)

My test code:
```
public List<Result> GetResults()
{
    var excel = new ExcelQueryFactory(@"c:\aaa\PR17R5570.xlsx");
    excel.AddMapping<Result>(x => x.SampleId, "Testprobe Nr.");
    excel.AddMapping<Result>(x => x.Value, "Ergebniss");
    var results = from r in excel.Worksheet<Result>("List1") select r;
    return results.ToList();
}
```

**Comment by mrworkman** [comment]
See the discussion in #68, and see if the solution provided there (using a # instead of a .) helps.

**Comment by mrworkman** [comment]
I will look into resolving this on #68.
