### ISSUE TITLE
Remove Support for Microsoft Jet 4

### ISSUE THREAD

**Issue by mrworkman** [paulyoder/LinqToExcel#131]
Microsoft Jet 4 was deprecated **15 years** ago, and doesn't even work in 64-bit processes. Remove support for Jet 4, and make ACE (backward compatible with Jet) a hard requirement.

**Comment by mrworkman** [comment]
Done.

**Comment by e-z-t** [comment]
Do you have plans to move the updated version to NuGet yet? Thank you.

**Comment by mrworkman** [comment]
> Do you have plans to move the updated version to NuGet yet? Thank you.

Soon. I need time to make more changes first.
