### ISSUE TITLE
LinqToExcel not in NuGet

### ISSUE THREAD

**Issue by Rod-in-NM** [paulyoder/LinqToExcel#133]
I just tried adding LinqToExcel through the VS 2017 NuGet Package Manager Console. It couldn't find it. Has it been removed/replaced?

**Comment by mrworkman** [comment]
It is still there. What kind of project are you targeting?

**Comment by Rod-in-NM** [comment]
You are correct, I did find it after you posted your message. Sorry I missed it before.

I'm just doing a simple console app.
