### ISSUE TITLE
Not a legal OleAut date 

### ISSUE THREAD

**Issue by sameerkattel** [paulyoder/LinqToExcel#135]
When I am trying to parse an excel file getting exception Not a legal OleAut date exception.

```
System.ArgumentException occurred
  HResult=-2147024809
  Message=Not a legal OleAut date.
  Source=mscorlib
  StackTrace:
       at System.DateTime.DoubleDateToTicks(Double value)
  InnerException: 
```

How do you force a column to be treated as a string type rather than date type?

**Comment by mrworkman** [comment]
Right now, because of the way Excel handles dates, you would have to open the file in Excel, and change the format of the column to "text" or "general".
