### ISSUE TITLE
GetWorksheetNames returns sorted list

### ISSUE THREAD

**Issue by crayxt** [paulyoder/LinqToExcel#153]
Good day,

I have noticed that list of Excel sheets returned by GetWorksheetNames is sorted alphabetically. Can this option be turned off?

Thanks,

**Comment by mrworkman** [comment]
I don't think this is possible in the current implementation. LinqForExcel uses OLEDB, which [does not preserve sheet order](http://social.msdn.microsoft.com/Forums/en/adodotnetdataproviders/thread/2f459200-deef-4131-be8a-1b67a41efb97). I took a look at the data provided during runtime, and, indeed, there's nothing indicating sheet the order. :(

**Comment by crayxt** [comment]
I suppose this is no longer actual.
