### ISSUE TITLE
Skip (trailing) empty lines

### ISSUE THREAD

**Issue by git-hub-user** [paulyoder/LinqToExcel#157]
Excel has a memory of which cell is de most lower right cell in use (which it jumps to when you type Ctrl-End). If you have removed lines from you document, this cell may be down far below the last line containing any values. 
When using LinkToExcel, the underlying provider will return lines up to the one containing the last cell. 
I can of course check if any of the cells contain data, but it would help me if I had a setting for this on the ExcelQueryFactory object. Something like `bool SkipEmptyLines`. It would be OK for me to also skip empty lines in the middle of the data set.

**Comment by VerdonTrigance** [comment]
Agree. I also have situations where in the middle of file I get some sort of summary info instead of data. It would be great to have opportunity process such 'invalid' rows somehow.

**Comment by mrworkman** [comment]
Implemented by #177.
