### ISSUE TITLE
Please release new NuGet version

### ISSUE THREAD

**Issue by MagicAndre1981** [paulyoder/LinqToExcel#162]
Can you please release a new NuGet package version with SourceLink enabled to make it easier to debug the lib

**Comment by mrworkman** [comment]
@MagicAndre1981 - [Released](https://github.com/paulyoder/LinqToExcel/releases/tag/v2.0.0-PRERELEASE-2). It should appear on Nuget within an hour.

**Comment by MagicAndre1981** [comment]
thanks for the update, works fine and I can step into code via Source Link 👍 😍
