### ISSUE TITLE
Unable to read Excel file

### ISSUE THREAD

**Issue by weitzhandler** [paulyoder/LinqToExcel#17]
I'm getting this error as soon as I try to access the Excel file:

"The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine."

Does MS Excel have to be installed on my computer?

I'm on Win8x64, but I set the build of the current app to x86, do I have to install additional software?

**Comment by Feneck91** [comment]
You can directly bind class with ExcelDataReader like with LinqToExcel.
I have the same problem with OleDB provider (application in 64 bits and office in 32 bits) and I wrote an adpater to make ExcelDataReader work like LinqToExcel. Of course, not all functions are implemented but it's a good beginning...
Have a look to : [CodePlex-ExcelDataReader][1]


  [1]: http://%20https://exceldatareader.codeplex.com/discussions/658724
