### ISSUE TITLE
LinqToExcel Limited to 256 Columns?

### ISSUE THREAD

**Issue by jbrainerd** [paulyoder/LinqToExcel#172]
I have a spreadsheet with 266 columns I am pulling into an application via LinqToExcel.  It seems to be working great, EXCEPT, it appears that I am only getting 256 columns.  I pulled the LinqToExcel source down and debugged it, and it looks like the IDataReader.GetSchemaTable() call is returning only 256 column values.  I realize  that is a library call outside of LinqToExcel.  It just seems odd there would be such a limitation.
Am I confused, or is this actually a limitation?

**Comment by mrworkman** [comment]
Hi, it's actually a limitation of the underlying database driver. It's unfortunate, because this problem comes up for a lot of people. I would very much like to fix it, but it's a big undertaking, and I don't have time to work on anything outside of work right now. 😟

**Comment by mrworkman** [comment]
Closed, as this is expected/known behaviour.

**Comment by jbrainerd** [comment]
Stephen –

Thanks that’s what it looked like to me, too.  I often make mistakes, and I was hoping this was another one.

 

 

John
