### ISSUE TITLE
255 columns limit when reading .XLSX file

### ISSUE THREAD

**Issue by casbby** [paulyoder/LinqToExcel#22]
Hi, 

I am trying to use the WorksheetRangeNoHeader method with the input parameters like ("A1", "CAA10000",1) as a workaround on the 255 columns limit on the provider. While this method works in a others' cases( http://social.msdn.microsoft.com/Forums/en-US/cf21f1be-d6e8-4ed9-b977-d6876bf0cf06/import-data-from-excel-file-into-a-datatable-column-limit). It is not working for linqToExcel.

do you have a workaround for this limitation?

Thanks
Casbby

**Comment by subsci** [comment]
Yeah you should put this limitation front and center on your intro doc page. Of course it's obvious when one stops to think about it upon unexpectedly encountering it.  Nonetheless being silent on limitations like these when Excel itself supports over 16K columns is at worst negligent and at best a pain in the keister.

**Comment by kierenj** [comment]
Ouch, @subsci, consider your attitude.  This is a freely-available, open source project contributed by someone who didn't have to do it.  It's hard to me that you could justify complaining about such a thing.  It's a very kind thing that this is being offered at all.  I notice that you don't have any open source projects you've shared of your own.  Consider why that is and as a fellow human being, please consider the human being who has to read your comments.
