### ISSUE TITLE
GetColumnNames() 64 char limit

### ISSUE THREAD

**Issue by RandomUniqueName** [paulyoder/LinqToExcel#33]
Hi,

I am currently using the GetColumnNames() and it works great except for the fact that there is a char limit on the string it returns of 64. Is there a way I can make that limit a lot higher or set it to unlimited?

Kind regards,

RandomUniquename

**Comment by RandomUniqueName** [comment]
@paulyoder could you maybe delete my name from your last post now? I think I have waited long enough for it. ;) Also this issue can be closed as its not relevant anymore.

**Comment by paulyoder** [comment]
@RandomUniqueName done! :-)

**Comment by ScepticDope** [comment]
> (Don' forget to delete the previous edit version please.)

Thanks! You still forgot to delete the edit history. ;)

![Capture](https://user-images.githubusercontent.com/46745973/59132860-91fe0200-8976-11e9-87ba-c3b82b38b967.PNG)

**Comment by RandomUniqueName** [comment]
> (Don' forget to delete the previous edit version please.)

Thanks! You still forgot to delete the edit histories though. ;) You can open them and then hit delete.

![Capture](https://user-images.githubusercontent.com/2275451/59133016-ff119780-8976-11e9-9ee5-96a96370511c.PNG)

**Comment by RandomUniqueName** [comment]
On another note, nice to see we still had some courtesies like in mail on GitHub back in good old 2014. :smile:

**Comment by RandomUniqueName** [comment]
Thanks! On another note, nice to see we still had some courtesies like in mail on GitHub back in good old 2014. :smile:
