### ISSUE TITLE
64-bit LinqToExcel NuGet package?

### ISSUE THREAD

**Issue by doggy8088** [paulyoder/LinqToExcel#41]
Is there any 64-bit LinqToExcel NuGet package?

**Comment by b-rewired** [comment]
It seems that the 64-bit package still can't be located using the the NuGet Package Manager - I had to install it from the console.  Searching for "LinqToExcel" only turns up a single result.

**Comment by paulyoder** [comment]
@b-rewired You can locate it from the NuGet Package Manager by searching for `LinqToExcel_x64`

**Comment by b-rewired** [comment]
@paulyoder You're absolutely right - my mistake!  I am sorry to re-open this.  May I suggest you update the readme.markdown to include links to both NuGet packages?  The link to the Access engine is already there but when searching in the package manager for "LinqToExcel" it only turns up the 32-bit version.  I don't know if you can somehow address this - it's almost as though the 64-bit version doesn't want to be found.

[32-bit](https://www.nuget.org/packages/LinqToExcel)
[64-bit](https://www.nuget.org/packages/LinqToExcel_x64/)

Fantastic component, Paul!  I've been using it all morning and I'm impressed with your thoroughness.
