### ISSUE TITLE
Reading from .csv files

### ISSUE THREAD

**Issue by nitewulf** [paulyoder/LinqToExcel#49]
I'm trying to query a .csv file generated from an external system and some example data looks like:

"1230200",,"01","UST, LTD"

They system is putting quotes around fields that don't need them.  That is causing LinqToExcel to treat those fields as arrays.  I'm having to open the .csv files with excel and save them again as a .csv file to remove the unnecessary quotes so the line would look like:

1230200,,1,"UST, LTD"

which LinqToExcel reads happily.

Are there any configuration options that i'm missing to have LinqToExcel read my files correctly?

**Comment by usmanbinasif** [comment]
Hi,

Facing the same issue, is anyone found how to fix this ???

Regards,
UJ
