### ISSUE TITLE
Characters Not Allowed in Column Headers

### ISSUE THREAD

**Issue by wyattEpp** [paulyoder/LinqToExcel#63]
When certain characters are included in column headers, those columns are not recognized. If certain characters are reserved and this is functioning as intended, this should be included in documentation.

Example:
var excel = new ExcelQueryFactory(filePath);
excel.AddMapping<CheckInObject>(x => x.TubeBarcode, "Tube Barcode");
excel.AddMapping<CheckInObject>(x => x.Freezer, "Freezer No.");
excel.AddMapping<CheckInObject>(x => x.FreezerRack, "Freezer Rack");

When querying a range with the above headers, column "Freezer No." is not recognized, while all others are.

**Comment by devcrew** [comment]
Good day,

Please find attached an unrecognized character section that may be added to the README.md file.

[20190513_linqtoexcel_unrecognized-characters.txt](https://github.com/paulyoder/LinqToExcel/files/3172859/20190513_linqtoexcel_unrecognized-characters.txt)
