### ISSUE TITLE
Data not pulled from cell

### ISSUE THREAD

**Issue by paqogomez** [paulyoder/LinqToExcel#7]
What steps will reproduce the problem?
1. Run the attached project
2. Notice in the xlsx file (in the bin\Debug directory) the value in D12 has the value "TextPickLetters, ImageV, AudioChooseA"
3. Notice the console output.  The value from D12 is not displayed.

What is the expected output? What do you see instead?
The expected output is for the 11th section object to have its media names populated.  Instead an empty string is passed into the method.  This is presumably because the column next to it or values above it are empty.

What version of the product are you using? On what operating system?
Latest version from NuGet.  Should be in the project.
OS = Win 7

The file is attached back in the wiki
http://code.google.com/p/linqtoexcel/issues/detail?id=60

**Comment by Stavo343** [comment]
Paul - Thanks for this package. We had the same issue and it not working was not an acceptable solution to us. We added a couple of things so we could actually read each line. I'm sure there are a lot of errors and problems related to what we did, but we can now successfully read the file. See the changes at https://github.com/EynonSoftwareLLC/LinqToExcel/commit/e25478f029d3a9a3e53daf767f23030d345d2ddd
