### ISSUE TITLE
Mapping two tables in LinqToExcel

### ISSUE THREAD

**Issue by virenderkverma** [paulyoder/LinqToExcel#75]
Can you check this thread

http://stackoverflow.com/questions/29435203/mapping-two-tables-in-linqtoexcel

**Comment by ssathya** [comment]
You are better-off using excel do data de-normalization before you bring data to c# processing.

Recall I tried to do something similar and was going in circles.

**Comment by mrworkman** [comment]
The original SO post is gone. Closing as this issue is now impossible to investigate.
