### ISSUE TITLE
Issue in Live server while uploading the Excel file

### ISSUE THREAD

**Issue by Praneshjs** [paulyoder/LinqToExcel#77]
i am working in c#, mvc 4, VS 2012. 
here the code works fine in local system, testing server but the same code in live server is facing a issue while importing excel file. the page simply refreshes when i attempt to import an excel file. but i am able to import data from csv, mdb files. Any solution for this? i am using linqtoexcel.dll for this

**Comment by mrworkman** [comment]
This is extremely vague - much more detail is required. Closing due to the issue's age.
