### ISSUE TITLE
Unable to read CSV column headers

### ISSUE THREAD

**Issue by ryanpulliam** [paulyoder/LinqToExcel#83]
Currently the only way we've been able to get columnheaders for CSV files is to read the first record in the file using WorksheetNoHeader. The problem is for columns like "PostalCode", if the records thereafter are numeric: 63105, 63143, etc... then the PostalCode header is missing.  We have not found a way to get the column headers using GetColumnHeaders for CSV files.

```cs
List<LinqToExcel.RowNoHeader> spreadsheetRows = (from c in spreadsheet.WorksheetNoHeader()
                                                                 select c).ToList();
                if (spreadsheetRows != null && spreadsheetRows.Count > 0)
                {
                    List<LinqToExcel.Cell> spreadsheetCells = spreadsheetRows[0];
                    if (spreadsheetCells != null && spreadsheetCells.Count > 0)
                    {
                        foreach (LinqToExcel.Cell spreadsheetCell in spreadsheetCells)
                        {
                            spreadsheetColumnNames.Add(spreadsheetCell.Value.ToString());
                        }
                    }
                }
```

**Comment by desertrambler** [comment]
This is still broken. Is there any estimate as to when this will be fixed?

**Comment by mrworkman** [comment]
I strongly recommend using something like CSV Helper (https://joshclose.github.io/CsvHelper/) for reading CSV. LinqToExcel only offers basic CSV support.
