### ISSUE TITLE
Featre Request: Switch from log4net to something more generalized (like Serilog)

### ISSUE THREAD

**Issue by ravensorb** [paulyoder/LinqToExcel#88]
It would be very helpful if there wasn't a hard dependency on a specific logging framework (I do not really use log4net).  Any thought to switching over to something like Serilog that allows for multiple different logging frameworks to be "plugged in"?

**Comment by Yustos** [comment]
+1

**Comment by mrworkman** [comment]
Non-issue as of PR #107.
