### ISSUE TITLE
LinkToExcel with asp.net core

### ISSUE THREAD

**Issue by typae** [paulyoder/LinqToExcel#95]
The dependency LinkToExcel 1.10.1 in project "ProjectName" does not support framework DNXCore,Version=v5.0.
I get this message from the project.json after adding via nuget.
Any way to fix it?

**Comment by saitonakamura** [comment]
Try to rebuild it under DNX from sources
But i'm not sure that `System.Data.OleDb` will work as expected

**Comment by mrworkman** [comment]
Core is not supported.

**Comment by mjhpour** [comment]
Please add support for ASP .Net Core.
